### ISSUE TITLE
'npm start' fails with an error

### ISSUE THREAD

**Issue by jvpichowski** [TelestionTeam/telestion-rocketsound-psc#71]
I wanted to start the application after a clean pull from main and called `npm ci` and `npm start`. Then I got the following stack trace:

```
npm start

> telestion-rocketsound-psc@0.2.0 start C:\Users\...\telestion-rocketsound-psc
> npm run start:electron


> telestion-rocketsound-psc@0.2.0 start:electron C:\Users\...\telestion-rocketsound-psc
> tc-cli start --electron

C:\Users\...\telestion-rocketsound-psc\node_modules\@wuespace\telestion-client-cli\src\commands\build.js:29
                await compileElectronMainThread(projectRoot, config?.plugins || []);
                                                                    ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at Object.require (internal/modules/cjs/helpers.js:72:18)
    at C:\Users\...\telestion-rocketsound-psc\node_modules\require-directory\index.js:76:17
    at Array.forEach (<anonymous>)
    at Object.requireDirectory (C:\Users\...\telestion-rocketsound-psc\node_modules\require-directory\index.js:59:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telestion-rocketsound-psc@0.2.0 start:electron: `tc-cli start --electron`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the telestion-rocketsound-psc@0.2.0 start:electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2021-03-10T10_38_18_651Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telestion-rocketsound-psc@0.2.0 start: `npm run start:electron`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the telestion-rocketsound-psc@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2021-03-10T10_38_18_674Z-debug.log
```

Note: I removed my username from the logs. Do you need additional information like some logs?

**Comment by pklaschka** [comment]
You probably need to update your NodeJS version (14+) 😉 

Please feel free to re-open if that doesn't work.

**Comment by jvpichowski** [comment]
Thanks. It works. Probably a notice with all needed dependencies would be good inside the readme.
